#ifndef BUFFER_SIZE_H
#define BUFFER_SIZE_H


#define ENCLAVE_OUTPUT_BUFFER 10  // in KB
#define ENCLAVE_READ_BUFFER 10    // in KB
#define MAX_CLIENTNAME_LENGTH 30
#define BUFFER_UPDATE_INTERVAL 10  // in milliseconds

#define ENCLAVE_OUTPUT_BUFFER_SIZE ENCLAVE_OUTPUT_BUFFER * 1024  // in B

#define ENCLAVE_READ_BUFFER_SIZE ENCLAVE_READ_BUFFER * 1024  // in B

#endif